-- MySQL Script generated by MySQL Workbench
-- Mon Feb 25 20:58:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema webbanhang
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `webbanhang` ;

-- -----------------------------------------------------
-- Schema webbanhang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webbanhang` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `webbanhang` ;

-- -----------------------------------------------------
-- Table `webbanhang`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`user_role` (
  `user_role_id` INT NOT NULL AUTO_INCREMENT,
  `user_role_name` NVARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`user_role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webbanhang`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`user` (
  `user_id` VARCHAR(36) NOT NULL,
  `username` NVARCHAR(30) NOT NULL,
  `password` NVARCHAR(30) NOT NULL,
  `email` NVARCHAR(45) NOT NULL,
  `user_role_user_role_id` INT NOT NULL,
  `address` NVARCHAR(100) NULL,
  `phone` VARCHAR(12) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_bin_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_user_user_role1_idx` (`user_role_user_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`user_role_user_role_id`)
    REFERENCES `webbanhang`.`user_role` (`user_role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `webbanhang`.`product_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`product_material` (
  `product_material_id` INT NOT NULL AUTO_INCREMENT,
  `product_material_name` NVARCHAR(45) NULL,
  PRIMARY KEY (`product_material_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webbanhang`.`product_origin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`product_origin` (
  `product_origin_id` INT NOT NULL AUTO_INCREMENT,
  `product_origin_name` NVARCHAR(45) NULL,
  PRIMARY KEY (`product_origin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webbanhang`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`product_type` (
  `product_type_id` INT NOT NULL AUTO_INCREMENT,
  `product_type_name` NVARCHAR(45) NULL,
  PRIMARY KEY (`product_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webbanhang`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`product` (
  `product_id` VARCHAR(36) NOT NULL,
  `product_name` NVARCHAR(45) NULL,
  `product_type_product_type_id` INT NOT NULL,
  `product_material_product_material_id` INT NOT NULL,
  `product_origin_product_origin_id` INT NOT NULL,
  `shortname` NVARCHAR(45) NULL,
  `thumbnail` NVARCHAR(45) NULL,
  `description` TEXT NULL,
  `quantity` INT NULL,
  `price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_product_product_material_idx` (`product_material_product_material_id` ASC) VISIBLE,
  INDEX `fk_product_product_origin1_idx` (`product_origin_product_origin_id` ASC) VISIBLE,
  INDEX `fk_product_product_type1_idx` (`product_type_product_type_id` ASC) VISIBLE,
  UNIQUE INDEX `product_id_bin_UNIQUE` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_product_material`
    FOREIGN KEY (`product_material_product_material_id`)
    REFERENCES `webbanhang`.`product_material` (`product_material_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_product_origin1`
    FOREIGN KEY (`product_origin_product_origin_id`)
    REFERENCES `webbanhang`.`product_origin` (`product_origin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_product_type1`
    FOREIGN KEY (`product_type_product_type_id`)
    REFERENCES `webbanhang`.`product_type` (`product_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webbanhang`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`order` (
  `order_id` VARCHAR(36) NOT NULL,
  `user_user_id` VARCHAR(36) NOT NULL,
  `order_date` DATETIME NULL,
  `address` NVARCHAR(100) NULL,
  `phone` VARCHAR(12) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `webbanhang`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webbanhang`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`order_detail` (
  `product_product_id` VARCHAR(36) NOT NULL,
  `order_order_id` VARCHAR(36) NOT NULL,
  `quantity` INT NULL,
  `price` DECIMAL(10,2) NULL,
  `total` DECIMAL(10,2) GENERATED ALWAYS AS (`quantity` * `price`) VIRTUAL,
  PRIMARY KEY (`product_product_id`, `order_order_id`),
  INDEX `fk_order_detail_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `webbanhang`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_detail_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `webbanhang`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webbanhang`.`product_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webbanhang`.`product_img` (
  `product_product_id` VARCHAR(36) NOT NULL,
  `img_name` NVARCHAR(45) NOT NULL,
  UNIQUE INDEX `img_name_UNIQUE` (`img_name` ASC) VISIBLE,
  INDEX `fk_product_img_product1_idx` (`product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_img_product1`
    FOREIGN KEY (`product_product_id`)
    REFERENCES `webbanhang`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `webbanhang`;

DELIMITER $$
USE `webbanhang`$$
CREATE
DEFINER=CURRENT_USER
TRIGGER `webbanhang`.`user_BEFORE_INSERT`
BEFORE INSERT ON `webbanhang`.`user`
FOR EACH ROW
BEGIN
	if new.user_id is null then
		set new.user_id = UUID();
        end if;
END$$

USE `webbanhang`$$
CREATE DEFINER = CURRENT_USER TRIGGER `webbanhang`.`product_BEFORE_INSERT` BEFORE INSERT ON `product` FOR EACH ROW
BEGIN
	if new.product_id is null then
		set new.product_id = UUID();
    end if;
END$$

USE `webbanhang`$$
CREATE DEFINER = CURRENT_USER TRIGGER `webbanhang`.`order_BEFORE_INSERT` BEFORE INSERT ON `order` FOR EACH ROW
BEGIN
if new.order_id is null then
		set new.order_id = UUID();
    end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
